---
version: '3'
services:
  app:
    build: .
    links:
      - postgres
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres
    ports:
      - "5432:5432"
